-- INSERTAR VALORES --
-- Hay que ingresar como usr_acuario para poder hacer un insert
-- ============================================================================================================================
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (1, 'Aguascalientes');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (2, 'Baja California');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (3, 'Baja California Sur');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (4, 'Campeche');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (5, 'Chiapas');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (6, 'Chihuahua');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (7, 'Ciudad de México');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (8, 'Coahuila');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (9, 'Colima');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (10, 'Durango');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (11, 'Estado de México');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (12, 'Guanajuato');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (13, 'Guerrero');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (14, 'Hidalgo');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (15, 'Jalisco');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (16, 'Michoacán');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (17, 'Morelos');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (18, 'Nayarit');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (19, 'Nuevo León');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (20, 'Oaxaca');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (21, 'Puebla');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (22, 'Querétaro');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (23, 'Quintana Roo');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (24, 'San Luis Potosí');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (25, 'Sinaloa');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (26, 'Sonora');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (27, 'Tabasco');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (28, 'Tamaulipas');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (29, 'Tlaxcala');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (30, 'Veracruz');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (31, 'Yucatán');
INSERT INTO ESTADO (ID_ESTADO, NOMBRE_ESTADO) VALUES (32, 'Zacatecas');
-- ============================================================================================================================
INSERT INTO PELIGRO (ID_PELIGRO, PELIGRO) VALUES (1, 'Sin riesgo');
INSERT INTO PELIGRO (ID_PELIGRO, PELIGRO) VALUES (2, 'Bajo riesgo');
INSERT INTO PELIGRO (ID_PELIGRO, PELIGRO) VALUES (3, 'Amenazada');
INSERT INTO PELIGRO (ID_PELIGRO, PELIGRO) VALUES (4, 'Extinta en estado silvestre');
-- ============================================================================================================================
INSERT INTO ALIMENTACION (ID_ALIMENTACION, ALIMENTACION) VALUES (1, 'Hervivoro');
INSERT INTO ALIMENTACION (ID_ALIMENTACION, ALIMENTACION) VALUES (2, 'Carnivoro');
INSERT INTO ALIMENTACION (ID_ALIMENTACION, ALIMENTACION) VALUES (3, 'Omnivoro');
-- ============================================================================================================================
INSERT INTO TIPO_AGUA (ID_TIPO_DE_AGUA, TIPO_DE_AGUA) VALUES (1, 'Dulce');
INSERT INTO TIPO_AGUA (ID_TIPO_DE_AGUA, TIPO_DE_AGUA) VALUES (2, 'Salada');
-- ============================================================================================================================
INSERT INTO MATERIAL (ID_MATERIAL, NOMBRE_MATERIAL) VALUES (1, 'Vidrio');
INSERT INTO MATERIAL (ID_MATERIAL, NOMBRE_MATERIAL) VALUES (2, 'Acrilico');
INSERT INTO MATERIAL (ID_MATERIAL, NOMBRE_MATERIAL) VALUES (3, 'Policarbonato');
-- ============================================================================================================================
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (1,'Pez payaso', 'Amphiprioninae', 'Pertenece al orden de los Persciformes (con forma de perca), y engloba cerca de 30 subespecies de peces payasos. Puede distinguirse a primera vista por poseer una hermosa combinación de color naranja con bandas blancas a cada extremo de su cuerpo y en el centro. Los bordes son de color negro, y en ocasiones su color predominante puede variar desde el rojo oscuro hasta tonalidades más claras. No obstante, existen ejemplares melánicos, que sustituyen el color naranja por el negro, otorgándoles un aspecto elegante y singular. De cualquier manera, la viveza de sus colores tan llamativos le ha convertido en una especie predilecta para los entusiastas de la acuariofilia a nivel mundial. Sobre este tema abordaremos más adelante en este artículo.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (2,'Pez cirujano azul', 'Paracanthurus hepatus', 'El pez cirujano (Acanthuridae) es un pez marino tropical de cuerpo profundo de la familia Acanthuridae (orden Perciformes). Los peces cirujanos son de pequeña escala, con una sola aleta dorsal y una o más espinas distintivas y afiladas que se encuentran a ambos lados de la base de la cola y pueden producir cortes profundos. Las espinas, que se asemejan al bisturí de un cirujano, pueden ser fijadas en su lugar o abisagradas en la parte posterior para que puedan abrirse hacia afuera y dirigirse hacia adelante.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (3,'Anémona marina', 'Actiniaria', 'Las anémonas son invertebrados de color rosa con aspecto vegetal y con largos tentáculos que se mueven. La anémona de mar, también conocida como fideos de mar, viven sobre rocas expuestas a la luz, frecuente desde la línea de mareas hasta los 6 m de profundidad. Se encuentra con frecuentemente en las aguas poco profundas de las bahías tranquilas y soporta bien las aguas sucias. ');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (4, 'Coral cuero', 'Sarcophyton trocheliophorum', 'De naturaleza robusta y apariencia erizada, tiene un tallo grueso, liso y simple, con una parte superior en forma de hongo acampanado y liso, que puede ser plegado, o en forma de embudo. Dependiendo de la especie, las colonias más jóvenes tienen forma de hongo y las colonias maduras son más lobuladas y dobladas como un hongo. Algunos mantienen el aspecto de las setas toda su vida.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (5, 'Tortuga de orejas rojas', 'Trachemys scripta elegans', 'La piel de una tortuga oreja roja es de color verde con rayas de color amarillo brillante. Un parche de color rojo se ubica detrás de cada ojo, lo que condiciona el nombre de la especie, aunque algunos ejemplares pueden carecer de este color. Algunas tortugas también pueden tener un pequeño parche de color rojo en la parte superior de sus cabezas. En promedio miden de 12 a 20 cm, las hembras suelen ser un poco más grandes que los machos y llegan a vivir entre 20 y 30 años.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (6, 'Tortuga de orejas amarillas', 'Trachemys scripta scripta', 'Caparazón de color negro con unas rayas verticales tenues de color marrón. El plastrón es amarillo, sin manchas o con unas pocas de color negro. La cabeza es oscura con unas grandes manchas de color amarillo intenso. Al nacer cuentan con un caparazón de 3cm, pero llegan a alcanzar los 28 cm. Los machos tienen las uñas mucho más largas y la cola también más larga y ancha. Las hembras suelen alcanzar mayor tamaño.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (7, 'Cangrejo ermitaño', 'Stenorhynchus seticornis', 'Los cangrejos ermitaños son animales carentes de coraza; los más grandes viven a lo largo de la costa del pacífico y alcanzan hasta 46 cm. Tienen cuatro pares de extremidades desarrolladas (incluyendo las pinzas). Introducen el abdomen en cubiertas de moluscos gasterópodos con las que cargan para protegerse.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (8, 'Piraña panza roja', 'Pygocentrus nattereri', 'Su tamaño ronda los 30 centímetros y de joven suele tener un color plateado con puntos negros que van desapareciendo con el paso del tiempo. Asimismo, conforme se van haciendo adultas, su lomo se va volviendo oscuro, su iris se torna a un naranja intenso y su barriga se va enrojeciendo, de ahí que a la piraña roja se le conozca como “red belly” en algunos países anglosajones.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (9, 'Medusa luna', 'Aurelia aurita', 'La umbrela de Aurelia aurita puede medir entre 20 y 40 cm de diámetro y tiene forma aplanada, lisa y sin dibujos. Su borde presenta numerosos tentáculos cortos y 8 ropalias dispuestas regularmente. A través de la umbrela se ven con claridad 4 gónadas en forma de herradura de color rosa azulado. Cuenta con 4 brazos bucales. Esta especie presenta en general un color transparente, con frecuencia rosa pálido, azul o violeta.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (10, 'Medusa bala de cañón', 'Stomolophus meleagris', 'La medusa bola de cañón posee una campana en forma de cúpula que mide apenas 25 cm de diámetro, donde destaca en ocasiones un borde coloreado en tonos marrón. Como una extensión del cuerpo se encuentran debajo de la boca un conjunto de brazos orales, que le ayudan como medio de propulsión y en la captura de las presas.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (11, 'Estrella de mar','Asterias rubens','Es un equinodermo acuático que habita en los océanos de todo el mundo. Tienen forma de estrella con varios brazos y pueden variar en color desde el rojo hasta el naranja y el amarillo');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (12, 'Cangrejo ermitaño','Paguroidea','Es un crustáceo acuático que habita en los océanos de todo el mundo. Tienen un cuerpo blando y utilizan las conchas de otros animales para protegerse y esconderse.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (13, 'Ballena jorobada','Megaptera novaeangliae','Una de las especies de ballenas más conocidas por sus habilidades acrobáticas y sus canciones complejas. Mide entre 12 y 16 metros de longitud y puede pesar hasta 36 toneladas. Su hábitat se encuentra en aguas tropicales y subtropicales.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (14, 'Mantaraya','Manta birostris','Un pez cartilaginoso de gran tamaño, que puede alcanzar los 7 metros de ancho. Su cuerpo plano y sus aletas pectorales lo hacen parecer un pájaro gigante en el agua. Alimenta de plancton y pequeños peces y habita en los océanos de todo el mundo.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (15, 'Pulpo de anillos azules','Hapalochlaena maculosa','Un pulpo pequeño que mide entre 7 y 10 cm y es conocido por su veneno altamente tóxico. Aunque su apariencia es relativamente discreta, es considerado uno de los animales más peligrosos del mundo. Se encuentra en las costas de Australia y Japón.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (16, 'Manatí antillano','Trichechus manatus','Un mamífero acuático herbívoro que habita en los ríos, lagos y costas de Centro y Sudamérica. Es conocido por ser muy amistoso y curioso. Su cuerpo es grande y cilíndrico, con una cola aplanada que utiliza para desplazarse en el agua.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (17, 'Narval','Monodon monoceros','Una ballena pequeña con un largo colmillo recto y puntiagudo, que puede medir hasta 3 metros. Vive en las aguas del Ártico y se alimenta de peces y calamares. Es conocido por su largo colmillo, que en realidad es un diente incisivo superior.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (18, 'Delfín nariz de botella','Tursiops truncatus','Una especie de delfín que se encuentra en los océanos Atlántico, Pacífico e Índico. Su cuerpo es alargado y su cabeza es redondeada, con un pico distintivo. Se alimenta de una variedad de peces y calamares.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (19, 'Pez globo','Tetraodontidae','	Una familia de peces que se encuentran en las aguas tropicales y subtropicales de todo el mundo. Tienen cuerpos redondos y inflables y son conocidos por su capacidad para inflarse para protegerse de los depredadores.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (20, 'Ostra europea','Ostrea edulis','Una especie de molusco bivalvo que se encuentra en las aguas costeras de Europa y el Mediterráneo. Es conocida por su carne sabrosa y se utiliza ampliamente en la cocina.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (21, 'Anguila eléctrica','Electrophorus electricus','Un pez eléctrico que se encuentra en los ríos y lagos de Sudamérica. Es conocido por su capacidad para generar una descarga eléctrica de hasta 600 voltios para defenderse de los depredadores o capturar presas.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (22, 'Tiburón blanco','Carcharodon carcharias','Un gran tiburón que se encuentra en los océanos de todo el mundo. Es conocido por su gran tamaño, su mandíbula llena de dientes afilados y su reputación como depredador peligroso.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (23, 'Pulpo','Octopus vulgaris','Un molusco cefalópodo que se encuentra en las aguas costeras de todo el mundo. Tiene un cuerpo redondo y flexible, con tentáculos largos y delgados. Se alimenta de una variedad de crustáceos y peces pequeños.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (24, 'Pez espada','Xiphias gladius','Un pez de gran tamaño que se encuentra en los océanos de todo el mundo. Tiene un cuerpo largo y delgado, con una mandíbula alargada llena de dientes afilados. Se alimenta de una variedad de peces y calamares.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (25, 'Pez loro','Scaridae spp.','Una familia de peces tropicales que se encuentran en los arrecifes de coral de todo el mundo. Tienen cuerpos alargados y coloridos, con mandíbulas fuertes que les permiten raspar la comida de las rocas y los corales.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (26, 'Aguja marina','Syngnathidae spp.','Una familia de peces de agua salada que se encuentran en todo el mundo. Tienen cuerpos delgados y alargados, con bocas pequeñas y tubulares. Algunas especies son conocidas por su capacidad para camuflarse.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (27, 'Medusa avispa','Chironex fleckeri','Una medusa venenosa que se encuentra en las aguas costeras del norte de Australia y el sudeste asiático. Es conocida por su capacidad para infligir una picadura muy dolorosa que puede ser mortal para los humanos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (28, 'Langosta','Homarus americanus','Un crustáceo que se encuentra en las aguas costeras del Atlántico Norte. Tiene un cuerpo grande y fuerte, con garras grandes y poderosas que utiliza para defenderse y atrapar a sus presas.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (29, 'Calamar gigante','Architeuthis dux','Un cefalópodo gigante que se encuentra en las profundidades del océano en todo el mundo. Es conocido por su gran');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (30, 'Guppy', 'Poecilia reticulata','Peque�o pez tropical muy popular en acuariofilia por su facilidad decuidado y reproducci�n. Los machos presentan colores brillantes y variados en sus aletas y cuerpo, mientras que las hembras son m�s opacas y grandes. Los guppies son excelentes compa�eros de acuario y pueden coexistir con otras especies pac�ficas.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (31, 'Corydora', 'Corydoras paleatus', 'Pez de fondo muy popular en acuariofilia por su aspecto y comportamiento interesante. Poseen un cuerpo rechoncho y aletas grandes, y se alimentan de restos de comida y materia org�nica del sustrato. Son muy pac�ficos y pueden convivir con otras especies de su tama�o. Es recomendable mantenerlos en grupos de al menos 6 individuos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (32, 'Pez �ngel', 'Pterophyllum scalare', 'Elegante pez de acuario que pertenece a la familia Cichlidae. Su cuerpo tiene una forma triangular y las aletas son alargadas y puntiagudas. Los peces �ngel presentan una gran variedad de colores y patrones, y pueden alcanzar hasta los 15 cm de longitud. Es importante tener en cuenta que son territoriales y pueden llegar a ser agresivos con otras especies. Se recomienda mantenerlos en acuarios grandes y con plantas para crear zonas de refugio.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (33, 'Guppy', 'Poecilia reticulata', 'Pez de agua dulce originario de Sudam�rica que se caracteriza por sus colores  brillantes y variados.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (34, 'Tetra ne�n', 'Paracheirodon innesi','Pez peque�o y pac�fico de agua dulce que se distingue por su cuerpo alargado y sus colores brillantes y llamativos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (35, 'Corydora', 'Corydoras spp.', 'Pez de agua dulce muy popular en la acuariofilia por su comportamiento pac�fico y su capacidad para limpiar el sustrato.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (36, 'Anguila el�ctrica', 'Electrophorus electricus', 'Pez de agua dulce que habita en r�os y lagunas de Am�rica del Sur y se caracteriza por ser capaz de producir descargas el�ctricas para defenderse y capturar presas.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (37, 'Betta', 'Betta splendens', 'Pez de agua dulce originario del sudeste asi�tico que se distingue por sus aletas grandes y vistosas.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (38, 'C�clido convicto', 'Amatitlania nigrofasciata', 'Pez de agua dulce muy resistente y f�cil de mantener que se caracteriza por sus rayas negras y blancas.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (39, 'Pez �ngel', 'Pterophyllum scalare','Pez de agua dulce muy popular en la acuariofilia por su elegante forma y sus colores vistosos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (40, 'Pez globo', 'Tetraodontidae', 'Pez de agua salada que se infla como defensa contra los depredadores.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (41, 'Estrella de mar', 'Asterias rubens', 'Especie de equinodermo que se encuentra en el oc�ano Atl�ntico y se alimenta de moluscos y crust�ceos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (42, 'Corydora panda', 'Corydoras panda', 'Pez de fondo con un cuerpo peque�o y ovalado, de color blanco y negro. Debe mantenerse en grupos de al menos cinco individuos y su dieta debe incluir alimentos vivos y secos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (43, 'Gurami enano', 'Trichogaster lalius', 'Peque�o pez de agua dulce con cuerpo alargado y colores brillantes en tonos azules, rojos y verdes. Es una especie pac�fica que se lleva bien con otras especies de su mismo tama�o.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (44, 'Guppy', 'Poecilia reticulata', 'Pez peque�o y vivaz, de cuerpo alargado y colores brillantes. Es una especie muy popular en acuariofilia debido a su facilidad de reproducci�n y la gran variedad de colores y patrones que pueden presentar.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (45, 'Betta', 'Betta splendens', 'Pez de agua dulce con cuerpo alargado y colores vibrantes. Es una especie territorial y agresiva, por lo que es recomendable mantener un solo macho en un acuario o una hembra con varios machos. Su cuidado requiere de agua tibia y limpia y una dieta variada.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (46, 'Cangrejo enano', 'Cambarellus diminutus', 'Cangrejo peque�o y pac�fico, ideal para acuarios peque�os. Es una especie omn�vora que se alimenta de alimentos comerciales para cangrejos y restos de comida. Debe mantenerse en acuarios con suficientes escondites y refugios.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (47, 'C�clido enano', 'Apistogramma cacatuoides', 'Pez de agua dulce con cuerpo peque�o y colores brillantes. Es una especie territorial que debe mantenerse en parejas o en grupos de varias hembras y un macho. Su dieta debe incluir alimentos vivos y secos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (48, 'Carp�n dorado', 'Carassius auratus', 'Pez de agua fr�a y cuerpo alargado, de color dorado o plateado. Es una especie resistente y f�cil de cuidar, pero requiere de un acuario grande y bien filtrado. Su dieta debe incluir alimentos vivos y secos.');
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE_COMUN, NOMBRE_CIENTIFICO, DESCRIPCION) VALUES (49, 'Pez disco', 'Symphysodon spp.', 'Es una especie de pez de agua dulce originario de la cuenca del r�o Amazonas en Sudam�rica. Destaca por su cuerpo plano y redondeado, as� como por la variedad de colores y patrones que pueden presentar. Se considera una especie de acuario altamente demandada por su belleza y elegancia. Son peces territoriales y sociales, por lo que se recomienda mantenerlos en grupos de al menos 5 individuos.');
-- ============================================================================================================================
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (1, 'Gusanos marinos', 40, 200, 50, 'Tempor laboris elit ipsum ut nostrud enim exercitation occaecat voluptate velit duis minim dolore nostrud. Consectetur exercitation elit deserunt excepteur ullamco velit magna elit. Minim tempor exercitation excepteur ipsum eu exercitation consectetur laboris', 22.5, 6.5, 1, 1);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (2, 'Reptiles', 100, 300, 100, 'Reprehenderit minim elit ea laboris magna. Dolore incididunt velit velit ut incididunt laborum esse id. Ea labore quis ex aliqua esse laborum.', 23, 7, 1, 2);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (3, 'Poríferos', 300,700, 200, 'Tempor mollit ad est qui ex mollit nisi nisi laborum sunt magna enim sunt. Id reprehenderit elit cillum dolore nostrud duis tempor veniam. Velit nisi pariatur cupidatat sint deserunt elit.', 24.5, 7, 2, 2);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (4, 'Equinodermos', 200, 400, 70, 'Adipisicing est velit id aliqua deserunt aliquip tempor officia ullamco in cillum mollit cupidatat. Non fugiat veniam et voluptate sint proident qui. Excepteur duis commodo occaecat non commodo mollit mollit eiusmod. Consequat dolore sint ad qui dolor laborum occaecat ullamco Lorem labore laborum ea veniam. Eu nostrud veniam aute laboris ea consequat sint nulla id amet dolor eiusmod mollit irure. Dolore Lorem anim dolore fugiat sunt magna et do ex.', 23.5, 7.5, 2, 1);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (5, 'Mamíferos', 500, 1000, 150, 'Labore fugiat in deserunt ea aute aliquip ad officia laborum. Amet dolor aute velit duis ullamco duis dolore. Veniam aliqua velit culpa reprehenderit nulla. Exercitation esse id velit id mollit aliqua eu laborum adipisicing ut. Sit velit occaecat nisi amet id eiusmod et voluptate dolor dolor amet tempor quis. Proident ut commodo aliquip aute anim reprehenderit minim nostrud incididunt eiusmod laboris ad sint nostrud.', 24, 6.3, 1, 2);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (6, 'Cetáceos', 1000,2000,500,'Especies grandes',22.5,7,1,2);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (7, 'Peces', 60, 120, 70, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 25.5, 7.0, 2, 3);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (8, 'Moluscos', 30, 80, 40, 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 18.0, 6.8, 1, 2);
INSERT INTO HABITAT (ID_HABITAT, NOMBRE_HABITAT, ANCHO, LARGO, ALTO, DESCRIPCION, TEMPERATURATURA, PH_AGUA, ID_TIPO_DE_AGUA, ID_MATERIAL) VALUES (9, 'Rotíferos', 50, 150, 60, 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 20.5, 7.2, 2, 1);
-- ============================================================================================================================
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (1, 'Veracruz', 'Ricardo Flores Magón', 91900, 'Blvd. Manuel Ávila Camacho', 30);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, ID_ESTADO) VALUES (2, 'Acapulco de Juarez', 'Progreso', 39350, 'Articulo 27', 39, 13);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, ID_ESTADO) VALUES (3, 'Miguel Hidalgo', 'Granada', 11500, 'Miguel De Cervantes Savedra', 386, 7);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (4, 'Benito Juárez', 'Colonia del valle', 03100, 'Av.Insulgentes Sur', 1378, 9, 7);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (5, 'Acapulco de Juárez', 'Colonia centro', 39300, 'Calle Miguel Alemán', 143, 4103, 13);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (6, 'Xalapa', 'Colonia Centro', 91000, 'Calle Ignacio de la Llave', 267, 13, 30);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (7, 'Coyoacan', 'Villa Coyoacan', 04000, 'Higuera', 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (8, 'Tijuana', 'Centro', 22000, 'Calle Segunda', 2);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (9, 'Zapopan', 'La Estancia', 45030, 'Avenida Patria', 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (10, 'Coyoacan', 'Pedregal de Santo Domingo', 04369, 'Calle Pumawaka', 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (11, 'Monterrey', 'Contry La Silla', 64890, 'Av. Revolución', 19);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (12, 'Tlalnepantla', 'Loma de Sotelo', 54020, 'Circuito Misioneros', 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (13, 'Guadalajara', 'La Calma', 45070, 'Av. Mariano Otero', 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, ID_ESTADO) VALUES (14, 'Acapulco', 'Costa Azul', 39850, 'Av. Costera Miguel Alemán', 12);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (15, 'Ciudad de Mexico', 'Napoles', 03810, 'Calle Nebraska', 212, 15, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, ID_ESTADO) VALUES (16, 'Tijuana', 'Otay Constituyentes', 22455, 'Calle de los Insurgentes', 1782, 2);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (17, 'Guadalajara', 'Lomas de Polanco', 44960, 'Calle San Ignacio', 43, 4, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, ID_ESTADO) VALUES (18, 'Monterrey', 'La Estanzuela', 64988, 'Calle de la Monta�a', 109, 19);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, ID_ESTADO) VALUES (19, 'Cancun', 'Smz 50', 77533, 'Calle Punta Nizuc', 10, 23);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, ID_ESTADO) VALUES (20, 'Puebla', 'Centro Historico', 72000, 'Calle 5 de Mayo', 101, 21);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (21, 'Coyoacán', 'Villa Coapa', 04960, 'Calle del Bosque', 123, 10, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (22, 'Gustavo A. Madero', 'Lindavista', 07300, 'Calle Morelos', 456, 22, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (23, 'Tlalpan', 'La Joya', 14250, 'Avenida Tlalpan', 789, 7, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (24, 'Benito Juárez', 'Del Valle Centro', 03100, 'Calle Parroquia', 321, 3, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (25, 'Miguel Hidalgo', 'Polanco', 11560, 'Calle Horacio', 234, 8, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (26, 'Cuauhtémoc', 'Roma Norte', 06700, 'Calle Orizaba', 567, 15, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (27, 'Álvaro Obregón', 'San Ángel', 01000, 'Avenida Revolución', 89, 14, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (28, 'Azcapotzalco', 'San Marcos', 02070, 'Calle 5 de Febrero', 432, 1, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (29, 'Iztacalco', 'Agrícola Oriental', 08500, 'Calle Oriente 249', 765, 7, 9);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (30, 'Tlalnepantla de Baz', 'San Rafael', 54150, 'Calle Morelos', 543, 14, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (31, 'Nezahualcóyotl', 'Vicente Villada', 57210, 'Avenida Chimalhuacán', 876, 2, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (32, 'Naucalpan de Juárez', 'San Francisco Chimalpa', 53250, 'Calle Echegaray', 912, 5, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (33, 'Ecatepec de Morelos', 'La Florida', 55250, 'Calle Tlalnepantla', 346, 38, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (34, 'Tultitlán', 'Los Reyes Ixtacala', 54945, 'Calle 16 de Septiembre', 798, 11, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (35, 'Atizapán de Zaragoza', 'Las Arboledas', 52950, 'Avenida Adolfo López Mateos', 643, 4, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (36, 'Huixquilucan', 'Jesús del Monte', 52764, 'Calle Vista Hermosa', 268, 9, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (37, 'Metepec', 'San Miguel Totocuitlapilco', 52140, 'Calle Venustiano Carranza', 109, 28, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (38, 'Toluca', 'San Bernardino', 50140, 'Calle de la Cruz', 523, 6, 15);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (39, 'Zapopan', 'Ciudad Granja', 45010, 'Avenida Vallarta', 1234, 94, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (40, 'Guadalajara', 'Centro', 44100, 'Calle Independencia', 567, 3, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (41, 'Tlaquepaque', 'La Loma', 45590, 'Calle de los Santos', 891, 12, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (42, 'El Salto', 'San José del Quince', 45680, 'Calle Jardines de la Cruz', 234, 48, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (43, 'Tonala', 'Lomas de San Gaspar', 45403, 'Calle 16 de Septiembre', 567, 14, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (44, 'Puerto Vallarta', 'Versalles', 48310, 'Avenida México', 890, 58, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (45, 'Tijuana', 'Zona Centro', 22000, 'Calle Primera', 111, 2, 1);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (46, 'Pachuca', 'San Antonio', 01000, 'Calle La Palma', 8, 1, 14);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (47, 'Veracruz', 'Colonia Iguanas', 02000, 'Calle Constitución', 456, 8, 30);
INSERT INTO DIRECCION (ID_DIRECCION, ALCALDIA_MUNICIPIO, COLONIA, CP, CALLE, NUMERO_EXTERIOR, NUMERO_INTERIOR, ID_ESTADO) VALUES (48, 'Coyoacán', 'Culhuacan', 04480, 'Avenida Santa Ana', 789, 12, 3);
-- ============================================================================================================================
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (1, 'usuario1@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (2, 'usuario2@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (3, 'usuario3@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (4, 'usuario4@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (5, 'usuario5@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (6, 'usuario6@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (7, 'usuario7@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (8, 'usuario8@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (9, 'usuario9@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (10, 'usuario10@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (11, 'usuario11@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (12, 'usuario12@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (13, 'usuario13@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (14, 'usuario14@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (15, 'usuario15@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (16, 'usuario16@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (17, 'usuario17@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (18, 'usuario18@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (19, 'usuario19@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (20, 'usuario20@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (21, 'usuario21@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (22, 'usuario22@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (23, 'usuario23@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (24, 'usuario24@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (25, 'usuario25@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (26, 'usuario26@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (27, 'usuario27@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (28, 'usuario28@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (29, 'usuario29@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (30, 'usuario30@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (31, 'usuario31@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (32, 'usuario32@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (33, 'usuario33@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (34, 'usuario34@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (35, 'usuario35@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (36, 'usuario36@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (37, 'usuario37@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (38, 'usuario38@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (39, 'usuario39@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (40, 'usuario40@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (41, 'usuario41@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (42, 'usuario42@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (43, 'usuario43@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (44, 'usuario44@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (45, 'usuario45@outlook.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (46, 'usuario46@gmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (47, 'usuario47@hotmail.com');
INSERT INTO CORREO (ID_CORREO, CORREO) VALUES (48, 'usuario48@outlook.com');
-- ============================================================================================================================
INSERT INTO SUCURSAL (ID_SUCURSAL, NOMBRE_SUCURSAL, LADA, TELEFONO, EXTENSION, PAGINA_WEB, ID_DIRECCION, ID_CORREO) VALUES (1, 'Aquazul Veracruz', 22, 65284927, 1234, 'www.aquaver.com', 1, 1);
INSERT INTO SUCURSAL (ID_SUCURSAL, NOMBRE_SUCURSAL, LADA, TELEFONO, EXTENSION, PAGINA_WEB, ID_DIRECCION, ID_CORREO) VALUES (2, 'Aquazul Acapulco', 47, 37832882, 1243, 'www.aquaaca.com', 2, 2);
INSERT INTO SUCURSAL (ID_SUCURSAL, NOMBRE_SUCURSAL, LADA, TELEFONO, EXTENSION, PAGINA_WEB, ID_DIRECCION, ID_CORREO) VALUES (3, 'Aquazul CDMX', 55, 56702309, 3014, 'www.aquacdmx.com', 3, 3);
-- ============================================================================================================================
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (1, 'Besugo',5000 ,'Alimentar en grupo', 3, 2, 6, 15, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (2, 'Volatil',500 ,'Ponerle una roca encima', 2, 3, 6, 11, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (3, 'Nemo', 300,'Arrojar', 3, 1, 1, 1, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (4, 'Papa de Nemo', 300,'Arrojar', 3, 1, 1, 1, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (5, 'Rocky JR', 50,'Cuidado', 3, 1, 2, 20, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (6, 'Any', 150, 3, 4, 6, 14, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (7, 'Yna', 1500,'Separar de su madre', 3, 4, 6, 14, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (8, 'Rocky', 500,'Cuidado', 3, 1, 2, 20, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (9, 'Ecco',150, 3,1,1,24, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (10, 'Bolt', 700,'Cuidado', 2, 4, 3, 26, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (11, 'Trotuman',900,'Cuidado', 3, 1, 2, 6, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (12, 'Toto', 900, 3, 1, 2, 25, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (13, 'Max',1000,'Cuidado', 3, 1, 2, 23, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (14, 'Tota', 700, 3, 1, 2, 25, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (15, 'Trotuwomen',900,'Cuidado', 3, 1, 2, 6, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (16, 'Conan',700, 'Cuidado', 2, 4, 3, 26, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (17, 'Bob',10000,'Cuidado', 3, 1, 2, 23, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (18, 'Circus',100,'Cuidado', 1, 1, 2, 27, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (19, 'Pongo', 120,'Cuidado', 2, 4 ,3 ,30, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (20, 'Neo', 1200,'Cuidado', 2, 4 ,3 ,30, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (21, 'Toby', 120,'Cuidado', 2, 4 ,3 ,30, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (22, 'Arwen', 120,'Cuidado', 2, 4 ,3 ,30, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (23, 'Targaryen',5460,'Come mucho', 2, 4, 6, 15, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (24, 'Elsa',546,'Come mucho', 2, 4, 6, 15, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (25, 'Frodo',500,'Come mucho', 2, 4, 6, 15, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (26, 'Luke',900,'Come mucho', 2, 4, 6, 15, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (27, 'Arwen',800,1,2,2,12, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (28, 'Patricio',800,1,2,2,12, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (29, 'Yago',80,1,2,2,12, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (30, 'Samath',80,1,2,2,12, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (31, 'Pumba',85,1,2,2,12, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (32, 'Asael',354,1,2,2,12, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (33, 'Raven',465, 3,1,4,17, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (34, 'Luminoso',645, 3,1,4,16, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (35, 'Luz',600, 3,1,4,16, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (36, 'Rey', 50, 2, 4, 6, 23, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (37, 'Angel', 800, 3,4, 6, 7, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (38, 'Enrique', 500, 1 , 4, 6, 3, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (39, 'El Gera', 200, 2, 4, 6, 10, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (40, 'Bobjr', 200, 1, 2, 3, 42, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (41, 'Larry', 300, 'necesita agua caliente', 3, 2, 6, 48, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (42, 'Beto', 500, 3, 1, 4, 36, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (43, 'Crabzilla', 400, 'juega', 1, 2, 3, 33, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (44, 'Buddy', 300, 'Requiere agua con mayor ox�geno', 3, 1, 4, 35, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (45, 'Flash', 200, 'Requiere espacio para nadar', 3, 2, 2, 8, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (46, 'Rex', 60, 1, 1, 1, 31, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (47, 'Gus', 400, 1, 3, 5, 7, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (48, 'Bob', 200, 3, 2, 3, 42, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (49, 'Cleo', 50, 'Requiere una dieta espec�fica', 3, 3, 6, 44, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (50, 'Spike', 60, 1, 2, 5, 38, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (51, 'Nemo 2', 30, 2, 1, 1, 5, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (52, 'Gus', 400, 1, 4, 3, 42, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (53, 'Flash', 500, 'Requiere agua tibia', 1, 3, 2, 35, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (54, 'Gordo', 90, 'Necesita lugar para esconderse', 2, 2, 4, 44, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (55, 'Bubbles', 20, 'Es sensible a la luz', 2, 1, 1, 30, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (56, 'Razor', 800, 'Requiere agua salada', 1, 3, 6, 49, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (57, 'Tiger', 70, 'Necesita espacio para nadar', 3, 4, 3, 37, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (58, 'Ricky', 40, 'Necesita agua bien oxigenada', 3, 2, 1, 7, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (59, 'Jaws', 100, 'Requiere agua fr�a', 2, 4, 2, 45, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (60, 'Shadow', 300, 'Necesita un sustrato suave', 3, 1, 4, 32, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (61, 'Felix', 600, 'Es sensible a los cambios de temperatura', 1, 3, 4, 39, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (62, 'Lila', 50, 'Necesita una cueva para esconderse', 2, 1, 6, 43, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (63, 'Rocky jh', 200, 'No tolera niveles altos de nitrato', 3, 2, 1, 8, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (64, 'Kiwi', 300, 'Requiere agua con pH bajo', 1, 1, 5, 37, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (65, 'Bolt', 400, 'Necesita espacio para nadar', 1, 3, 6, 41, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (66, 'Luna', 60, 'Requiere luz tenue', 2, 1, 4, 36, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (67, 'Jazz', 300, 'No tolera agua caliente', 1, 2, 3, 31, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (68, 'Bam Bam', 800, 'Requiere una zona de arena en el acuario', 1, 1, 5, 46, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (69, 'Oliver', 50, 'No debe estar en contacto con otros peces de su especie', 1, 2, 2, 6, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (70, 'Sushi', 200, 'Necesita una roca para esconderse', 2, 3, 5, 34, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (71, 'Rudy', 700, 'Requiere corales en el acuario', 2, 1, 4, 36, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (72, 'Chispa', 40, 'Requiere un pH ligeramente �cido', 2, 1, 3, 34, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (73, 'Lenteja', 20, 3, 1, 1, 5, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (74, 'Misty', 600, 'Requiere agua salada', 2, 2, 6, 47, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (75, 'Oreo', 30, 'Necesita luz solar directa', 1, 1, 6, 38, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (76, 'Samba', 50, 'Requiere una temperatura constante de 20�C', 2, 3, 5, 39, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (77, 'Tico', 400, 1, 1, 4, 33, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (78, 'Zeus', 70, 'Necesita una cueva para esconderse', 1, 2, 5, 45, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (79, 'Emo', 20, 2, 1, 2, 8, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (80, 'Kiwi', 30, 'Necesita una piedra para afilarse las aletas', 1, 1, 4, 35, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (81, 'Bongo', 400, 2, 1, 6, 41, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (82, 'Minnie', 80, 'Necesita un escondite para descansar', 1, 3, 3, 6, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (83, 'Flash', 50, 'Es muy veloz y activo', 1, 2, 6, 10, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (84, 'Willy', 1000, 'Necesita agua salada', 2, 3, 1, 35, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (85, 'Kitty', 600, 'Es propensa a infecciones por hongos', 2, 1, 4, 41, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (86, 'Ciruela', 3000, 'Tiene una aleta lastimada', 2, 2, 5, 9, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (87, 'Ozzy', 70, 'No se lleva bien con otros peces', 1, 1, 4, 39, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (88, 'Bubbles', 90, 'Necesita un ambiente tranquilo', 2, 3, 2, 8, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (89, 'Sushi jr', 400, 'Es muy territorial', 1, 2, 4, 42, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (90, 'Buddy', 500, 'Necesita rocas en su h�bitat', 2, 1, 5, 31, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (91, 'Sparky', 60, 'Tiene un comportamiento nocturno', 1, 1, 1, 40, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (92, 'Lola', 120, 3, 2, 6, 38, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (93, 'Mickey', 800, 'Requiere una temperatura del agua de al menos 24�C', 2, 1, 3, 5, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (94, 'Chancla', 10000, 3, 4, 4, 42, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (95, 'Beto', 150, 'Necesita iluminaci�n adecuada para estimular su crecimiento', 3, 2, 1, 31, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (96, 'Olaf', 500, 'No es compatible con otros peces de su misma especie', 1, 3, 4, 47, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (97, 'Kiki', 70, 'Requiere agua salada', 2, 2, 5, 36, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (98, 'Paco', 120, 1, 1, 6, 33, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (99, 'Pan', 600, 'No es compatible con otros peces de colores similares', 1, 2, 5, 34, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (100, 'Dori', 90, 'Requiere una cueva para esconderse durante el d�a', 3, 1, 4, 37, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (101, 'Buddy', 110, 'Necesita un pH de agua espec�fico para sobrevivir', 1, 3, 2, 44, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (102, 'Chiquitin', 50, 'Requiere agua con pH mayor a 8.0', 3, 2, 4, 38, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (103, 'Pinky', 100, 3, 1, 6, 45, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (104, 'Beto', 800, 'Necesita rocas en su h�bitat', 1, 3, 1, 7, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (105, 'Luna', 6000, 2, 2, 5, 41, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (106, 'Ricky', 300, 'Requiere agua limpia con bajo nivel de nitratos', 2, 1, 3, 36, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (107, 'Lilo', 40, 'No debe tener compa�eros de su misma especie', 2, 4, 4, 47, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (108, 'Lucky', 150, 'Requiere agua a baja temperatura', 2, 3, 2, 31, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (109, 'Spike', 700, 'Requiere vegetaci�n en su h�bitat', 3, 2, 5, 48, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (110, 'Buddy', 120, 1, 1, 4, 44, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (111, 'Dory', 90, 'Necesita cuevas en su h�bitat', 2, 2, 6, 39, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (112, 'Tito', 60, 1, 2, 3, 9, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (113, 'Frida', 800, 'Requiere agua con pH 7.5-8.5', 2, 3, 6, 40, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (114, 'Pinky', 40, 3, 1, 1, 10, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (115, 'Dory', 100, 'Requiere agua con alta salinidad', 2, 2, 5, 8, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (116, 'Bubbles', 50, 3, 1, 2, 6, 1);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (117, 'Homero', 70, 1, 1, 5, 4, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, CONDICION_ESPECIAL, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (118, 'Flipper', 90, 'Requiere una corriente de agua moderada', 1, 2, 5, 37, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (119, 'Kirito', 600, 1, 1, 3, 9, 2);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (120, 'Ziggy', 80, 3, 3, 5, 40, 3);
INSERT INTO ANIMAL(ID_ANIMAL, NOMBRE_ANIMAL, CANTIDAD_DE_ALIMENTO, ID_ALIMENTACION, ID_PELIGRO, ID_HABITAT, ID_ESPECIE, ID_SUCURSAL) VALUES (121, 'Flounder', 400, 3, 1, 1, 30, 1);
-- ============================================================================================================================
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (1, 'Juan', 'García', 'González', 'Curador', 1, 47, 10);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (2, 'María', 'Rodríguez', 'Rodríguez', 'Biologo Marino', 1, 6, 11);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (3, 'Carlos', 'López', 'García', 'Veterinario', 1, 27, 18);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (4, 'Ana', 'Fernández', 'Martínez', 'Encargado de alimentación', 1, 7, 46);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (5, 'Miguel', 'González', 'Sánchez', 'Educador', 2, 28, 47);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (6, 'Lucía', 'Pérez', 'Pérez', 'Guía turistico', 2, 5, 48);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (7, 'David', 'Martínez', 'López', 'Técnico de acuario', 3, 29, 34);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (8, 'Laura', 'Sánchez', 'Fernández', 'Guardia de seguridad', 1, 20, 40);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (9, 'José', 'Gómez', 'Gómez', 'Personal de limpieza', 1, 45, 41);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (10, 'Sofía', 'Ruiz', 'Ruiz', 'Veterinario', 2, 12, 35);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (11, 'Manuel', 'Navarro', 'Alonso', 'Curador', 2, 30, 36);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (12, 'Elena', 'Romero', 'Álvarez', 'Encargado de alimentación', 2, 32, 37);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (13, 'Antonio', 'Moreno', 'Jiménez', 'Biologo Marino', 2, 31, 20);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (14, 'Patricia', 'Molina', 'Torres', 'Veterinario', 3, 39, 21);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (15, 'Pablo', 'Álvarez', 'Moreno', 'Personal de limpieza', 2, 38, 14);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (16, 'Marta', 'Jiménez', 'Castro', 'Guía turistico', 3, 40, 19);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (17, 'Javier', 'Delgado', 'Ramírez', 'Biologo Marino', 3, 41, 4);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (18, 'Cristina', 'Torres', 'Flores', 'Educador', 1, 48, 5);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (19, 'Luis', 'Serrano', 'Ortiz', 'Curador', 3, 46, 6);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (20, 'Isabel', 'Ortiz', 'Romero', 'Encargado de alimentación', 3, 44, 23);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (21, 'Fernando', 'Castro', 'Cruz', 'Personal de limpieza', 3, 42, 24);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (22, 'Beatriz', 'Morales', 'Vargas', 'Guía turistico', 1, 43, 25);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (23, 'Ignacio', 'Rubio', 'Delgado', 'Curador', 3, 4, 26);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (24, 'Clara', 'Ramírez', 'Medina', 'Educador', 3, 8, 27);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (25, 'Jorge', 'Medina', 'Herrera', 'Personal de limpieza', 1, 10, 28);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (26, 'Carmen', 'Herrera', 'Molina', 'Técnico de acuario', 1, 11, 29);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (27, 'Ángel', 'Flores', 'Mendoza', 'Veterinario', 1, 15, 30);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (28, 'Sara', 'Vargas', 'Aguilar', 'Personal de limpieza', 2, 21, 12);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (29, 'Francisco', 'Romero', 'Reyes', 'Biologo Marino', 1, 22, 13);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (30, 'Paula', 'Aguilar', 'Romero', 'Guardia de seguridad', 2, 23, 7);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (31, 'Rafael', 'Vega', 'González', 'Personal de limpieza', 3, 24, 8);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (32, 'Nuria', 'Muñoz', 'Ramos', 'Educador', 1, 9, 9);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (33, 'Sergio', 'Marín', 'Serrano', 'Guía turistico', 3, 13, 22);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (34, 'Eva', 'Moya', 'Velasco', 'Personal de limpieza', 1, 14, 17);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (35, 'Daniel', 'Castillo', 'Martín', 'Encargado de alimentación', 1, 17, 31);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (36, 'Martina', 'Zamora', 'Vega', 'Curador', 2, 18, 32);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (37, 'Alberto', 'Nieto', 'Cáceres', 'Encargado de alimentación', 2, 16, 33);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (38, 'Marta', 'Soler', 'Salazar', 'Guardia de seguridad', 3, 19, 45);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (39, 'Guillermo', 'Cáceres', 'Álvarez', 'Personal de limpieza', 2, 34, 15);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (40, 'Ainhoa', 'Gallego', 'Santos', 'Educador', 2, 35, 16);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (41, 'Diego', 'Ortega', 'Soler', 'Técnico de acuario', 2, 25, 38);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (42, 'Alba', 'Espinosa', 'Marín', 'Biologo Marino', 2, 26, 39);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (43, 'Jaime', 'Calvo', 'Flores', 'Encargado de alimentación', 3, 33, 42);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (44, 'Belén', 'Rivas', 'García', 'Educador', 3, 36, 43);
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO_PATERNO, APELLIDO_MATERNO, TIPO_DE_EMPLEADO, ID_SUCURSAL, ID_DIRECCION, ID_CORREO) VALUES (45, 'Ramón', 'Carmona', 'Núñez', 'Personal de limpieza', 3, 37, 44);
-- ============================================================================================================================
